"""PowerPoint deck generation.

The briefing counterpart to the Word report: the same grounded content, cut to
what fits on a screen in a turnaround meeting. A deck is not a report with
bigger fonts, so the spec is deliberately different — slides carry a small
number of bullets and one optional visual, and anything longer is the report's
job.

Two constraints shape the implementation:

Layouts are addressed by *index*, not by name. python-pptx's default template
names its layouts in English ("Title and Content"), but a deck built from a
customer template renames or reorders them, and looking a layout up by name
then raises at generation time on the customer's machine and nowhere else.
Indices 0/1/5/6 are stable positions in the standard master, and every access
falls back to the blank layout if the template is short.

Determinism matches :mod:`docx_builder`: core properties are stamped from
:func:`workbench.core.clock.now`, which is frozen under WORKBENCH_DETERMINISTIC
so the same inputs give byte-identical output.
"""

from __future__ import annotations

import io
import re
from typing import Any, Literal

from pydantic import BaseModel, Field

from workbench.artifacts.base import ArtifactBytes, ArtifactKind
from workbench.artifacts.provenance import AI_NOTICE, Provenance
from workbench.core.clock import now
from workbench.core.hashing import digest_bytes

#: Layout positions in the standard PowerPoint master.
_LAYOUT_TITLE = 0
_LAYOUT_TITLE_CONTENT = 1
_LAYOUT_TITLE_ONLY = 5
_LAYOUT_BLANK = 6

#: Beyond this, text stops being a slide and starts being a paragraph someone
#: will read aloud. Overflow moves to a continuation slide rather than shrinking
#: the font until it is unreadable on a projector.
MAX_BULLETS_PER_SLIDE = 7


class Slide(BaseModel):
    """One slide."""

    type: Literal["title", "bullets", "table", "image", "quote", "section"] = "bullets"
    title: str = ""
    subtitle: str = ""
    bullets: list[str] = Field(default_factory=list)
    #: Table rows, first row treated as the header.
    rows: list[list[str]] = Field(default_factory=list)
    #: Reference to a file produced by the sandbox, resolved by the caller.
    image_ref: str = ""
    caption: str = ""
    #: Shown in the footer, so a reviewer can trace a claim back without
    #: leaving the slide.
    notes: str = ""


class PptxSpec(BaseModel):
    title: str
    subtitle: str = ""
    classification: str = "internal"
    slides: list[Slide] = Field(default_factory=list)


class PptxBuilder:
    kind = ArtifactKind.PPTX

    def __init__(self, images: dict[str, bytes] | None = None) -> None:
        #: image_ref -> bytes, supplied by the caller from sandbox output.
        self.images = images or {}

    def build(self, spec: PptxSpec, provenance: Provenance) -> ArtifactBytes:
        from pptx import Presentation
        from pptx.util import Emu

        presentation = Presentation()
        self._width = presentation.slide_width or Emu(9144000)
        self._height = presentation.slide_height or Emu(6858000)

        self._title_slide(presentation, spec)

        rendered = 0
        for slide in spec.slides:
            rendered += self._render(presentation, slide, spec.classification)

        self._provenance_slides(presentation, provenance, spec.classification)

        buffer = io.BytesIO()
        presentation.core_properties.created = now()
        presentation.core_properties.modified = now()
        presentation.core_properties.author = "MRPL Sovereign AI Workbench"
        presentation.core_properties.title = spec.title
        presentation.save(buffer)

        data = buffer.getvalue()
        return ArtifactBytes(
            data=data,
            kind=self.kind,
            filename=self._filename(spec.title),
            sha256=digest_bytes(data),
            meta={
                "slides": len(presentation.slides),
                "requested_slides": len(spec.slides),
                "rendered_slides": rendered,
                "classification": spec.classification,
            },
        )

    # --- slide construction --------------------------------------------------

    def _layout(self, presentation: Any, index: int) -> Any:
        layouts = presentation.slide_layouts
        if index < len(layouts):
            return layouts[index]
        return layouts[min(_LAYOUT_BLANK, len(layouts) - 1)]

    def _title_slide(self, presentation: Any, spec: PptxSpec) -> None:
        from pptx.util import Pt

        slide = presentation.slides.add_slide(self._layout(presentation, _LAYOUT_TITLE))
        slide.shapes.title.text = spec.title
        placeholders = list(slide.placeholders)
        if len(placeholders) > 1:
            subtitle = spec.subtitle or "Generated by the MRPL Sovereign AI Workbench"
            placeholders[1].text = subtitle
            for paragraph in placeholders[1].text_frame.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(16)
        self._stamp(slide, spec.classification)

    def _render(self, presentation: Any, slide_spec: Slide, classification: str) -> int:
        """Render one spec entry. Returns the number of slides it produced."""
        if slide_spec.type == "section":
            return self._section(presentation, slide_spec, classification)
        if slide_spec.type == "table":
            return self._table(presentation, slide_spec, classification)
        if slide_spec.type == "image":
            return self._image(presentation, slide_spec, classification)
        if slide_spec.type == "quote":
            return self._quote(presentation, slide_spec, classification)
        return self._bullets(presentation, slide_spec, classification)

    def _section(self, presentation: Any, spec: Slide, classification: str) -> int:
        from pptx.util import Pt

        slide = presentation.slides.add_slide(self._layout(presentation, _LAYOUT_TITLE_ONLY))
        if slide.shapes.title is not None:
            slide.shapes.title.text = spec.title
            for paragraph in slide.shapes.title.text_frame.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(36)
        self._footer(slide, spec.notes)
        self._stamp(slide, classification)
        return 1

    def _bullets(self, presentation: Any, spec: Slide, classification: str) -> int:
        from pptx.util import Pt

        # Overflow continues onto further slides. Truncating would drop content
        # silently, and auto-shrinking produces a slide nobody at the back of
        # the room can read.
        chunks = [
            spec.bullets[index : index + MAX_BULLETS_PER_SLIDE]
            for index in range(0, len(spec.bullets), MAX_BULLETS_PER_SLIDE)
        ] or [[]]

        for position, chunk in enumerate(chunks):
            slide = presentation.slides.add_slide(self._layout(presentation, _LAYOUT_TITLE_CONTENT))
            heading = spec.title
            if position:
                heading = f"{spec.title} (cont.)"
            if slide.shapes.title is not None:
                slide.shapes.title.text = heading

            body = self._body_placeholder(slide)
            if body is not None:
                frame = body.text_frame
                frame.clear()
                for index, text in enumerate(chunk):
                    paragraph = frame.paragraphs[0] if index == 0 else frame.add_paragraph()
                    # A leading "- " or "* " is markdown leaking through from
                    # the model; the placeholder already draws the bullet.
                    paragraph.text = re.sub(r"^\s*[-*•]\s+", "", text)
                    paragraph.level = 0
                    for run in paragraph.runs:
                        run.font.size = Pt(18)

            if position == len(chunks) - 1:
                self._footer(slide, spec.notes)
            self._stamp(slide, classification)

        return len(chunks)

    def _table(self, presentation: Any, spec: Slide, classification: str) -> int:
        from pptx.util import Inches, Pt

        slide = presentation.slides.add_slide(self._layout(presentation, _LAYOUT_TITLE_ONLY))
        if slide.shapes.title is not None:
            slide.shapes.title.text = spec.title

        rows = spec.rows or [["(no data)"]]
        columns = max(len(row) for row in rows)
        # A slide fits far fewer rows than a page. Rather than render an
        # unreadable table, cut it and say so on the slide itself.
        visible = rows[:11]
        truncated = len(rows) - len(visible)

        left, top = Inches(0.6), Inches(1.8)
        width = self._width - Inches(1.2)
        height = Inches(0.35) * len(visible)
        shape = slide.shapes.add_table(len(visible), columns, left, top, width, height)
        table = shape.table

        for row_index, row in enumerate(visible):
            for column_index in range(columns):
                cell = table.cell(row_index, column_index)
                cell.text = row[column_index] if column_index < len(row) else ""
                for paragraph in cell.text_frame.paragraphs:
                    for run in paragraph.runs:
                        run.font.size = Pt(11)
                        run.font.bold = row_index == 0

        note = spec.notes
        if truncated > 0:
            omitted = f"{truncated} further row{'s' if truncated > 1 else ''} omitted — see the full report"
            note = f"{note} · {omitted}" if note else omitted
        self._footer(slide, note)
        self._stamp(slide, classification)
        return 1

    def _image(self, presentation: Any, spec: Slide, classification: str) -> int:
        from pptx.util import Inches, Pt

        slide = presentation.slides.add_slide(self._layout(presentation, _LAYOUT_TITLE_ONLY))
        if slide.shapes.title is not None:
            slide.shapes.title.text = spec.title

        payload = self.images.get(spec.image_ref)
        if payload:
            top = Inches(1.7)
            available = self._height - top - Inches(1.0)
            slide.shapes.add_picture(io.BytesIO(payload), Inches(1.2), top, height=available)
        else:
            # A missing image is stated on the slide. Rendering an empty frame
            # would let a chart silently vanish between the sandbox and the
            # deck, and the first person to notice would be the audience.
            box = slide.shapes.add_textbox(
                Inches(1.0), Inches(2.5), self._width - Inches(2.0), Inches(1.0)
            )
            paragraph = box.text_frame.paragraphs[0]
            paragraph.text = f"[image '{spec.image_ref}' was not produced]"
            for run in paragraph.runs:
                run.font.size = Pt(14)
                run.font.italic = True

        self._footer(slide, spec.caption or spec.notes)
        self._stamp(slide, classification)
        return 1

    def _quote(self, presentation: Any, spec: Slide, classification: str) -> int:
        from pptx.util import Inches, Pt

        slide = presentation.slides.add_slide(self._layout(presentation, _LAYOUT_BLANK))
        box = slide.shapes.add_textbox(
            Inches(1.2), Inches(2.0), self._width - Inches(2.4), Inches(2.5)
        )
        frame = box.text_frame
        frame.word_wrap = True
        paragraph = frame.paragraphs[0]
        paragraph.text = spec.title
        for run in paragraph.runs:
            run.font.size = Pt(24)
            run.font.italic = True
        if spec.subtitle:
            attribution = frame.add_paragraph()
            attribution.text = f"— {spec.subtitle}"
            for run in attribution.runs:
                run.font.size = Pt(14)
        self._footer(slide, spec.notes)
        self._stamp(slide, classification)
        return 1

    # --- provenance ----------------------------------------------------------

    def _provenance_slides(
        self, presentation: Any, provenance: Provenance, classification: str
    ) -> None:
        """The same record the Word report carries, at the end of the deck.

        A deck is the format most likely to be forwarded on its own, so the
        provenance travels inside it rather than in an accompanying file.
        """
        from pptx.util import Inches, Pt

        slide = presentation.slides.add_slide(self._layout(presentation, _LAYOUT_TITLE_ONLY))
        if slide.shapes.title is not None:
            slide.shapes.title.text = "Provenance"

        lines = provenance.lines()
        box = slide.shapes.add_textbox(
            Inches(0.6), Inches(1.6), self._width - Inches(1.2), Inches(4.0)
        )
        frame = box.text_frame
        frame.word_wrap = True
        first = True
        for label, value in lines:
            paragraph = frame.paragraphs[0] if first else frame.add_paragraph()
            first = False
            paragraph.text = f"{label}: {value}"
            for run in paragraph.runs:
                run.font.size = Pt(11)

        notice = frame.add_paragraph()
        notice.text = AI_NOTICE
        for run in notice.runs:
            run.font.size = Pt(9)
            run.font.italic = True

        if provenance.has_uncertain_sources:
            warning = frame.add_paragraph()
            warning.text = (
                "Some figures were read from scanned pages by OCR and may be "
                "inaccurate. Affected sources are marked below."
            )
            for run in warning.runs:
                run.font.size = Pt(10)
                run.font.bold = True
        self._stamp(slide, classification)

        # Sources get their own slide, and overflow onto more if the deck cited
        # widely. Silently dropping a source would be the one omission that
        # actually matters here.
        source_lines = provenance.source_lines() or [
            "No documents were cited. This content was not grounded in the indexed corpus."
        ]
        for position in range(0, len(source_lines), 8):
            chunk = source_lines[position : position + 8]
            slide = presentation.slides.add_slide(self._layout(presentation, _LAYOUT_TITLE_ONLY))
            if slide.shapes.title is not None:
                slide.shapes.title.text = "Sources" if position == 0 else "Sources (cont.)"
            box = slide.shapes.add_textbox(
                Inches(0.6), Inches(1.6), self._width - Inches(1.2), Inches(4.0)
            )
            frame = box.text_frame
            frame.word_wrap = True
            for index, line in enumerate(chunk):
                paragraph = frame.paragraphs[0] if index == 0 else frame.add_paragraph()
                paragraph.text = f"{position + index + 1}. {line}"
                for run in paragraph.runs:
                    run.font.size = Pt(11)
            self._stamp(slide, classification)

    # --- chrome --------------------------------------------------------------

    def _body_placeholder(self, slide: Any) -> Any:
        """The content placeholder, whatever index the template gave it."""
        for placeholder in slide.placeholders:
            if placeholder.placeholder_format.idx != 0:
                return placeholder
        return None

    def _stamp(self, slide: Any, classification: str) -> None:
        """Classification marking on every slide.

        Slides are extracted and re-pasted constantly, so the marking has to be
        on each one rather than on the cover.
        """
        from pptx.dml.color import RGBColor
        from pptx.util import Inches, Pt

        box = slide.shapes.add_textbox(
            Inches(0.3), Inches(0.08), self._width - Inches(0.6), Inches(0.3)
        )
        paragraph = box.text_frame.paragraphs[0]
        paragraph.text = f"MRPL — {classification.upper()}"
        for run in paragraph.runs:
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)

    def _footer(self, slide: Any, text: str) -> None:
        from pptx.dml.color import RGBColor
        from pptx.util import Inches, Pt

        if not text:
            return
        box = slide.shapes.add_textbox(
            Inches(0.6), self._height - Inches(0.75), self._width - Inches(1.2), Inches(0.5)
        )
        frame = box.text_frame
        frame.word_wrap = True
        paragraph = frame.paragraphs[0]
        paragraph.text = text
        for run in paragraph.runs:
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(0x60, 0x60, 0x60)

    @staticmethod
    def _filename(title: str) -> str:
        slug = re.sub(r"[^A-Za-z0-9]+", "-", title).strip("-")[:60] or "briefing"
        return f"{slug}.pptx"
